# 从菜鸟教程上面练习 Python 库的 Numpy 的使用

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

In [2]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [14]:
import numpy as np

a = np.arange(10, dtype=float)
print(a)
print(f'a.shape: {a.shape}')
print(f'a.ndim: {a.ndim}')
print(f'a[1]: {a[1]: .3f}')

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a.shape: (10,)
a.ndim: 1
a[1]:  1.000


In [19]:
import numpy as np

a = np.arange(start=1, stop=12, step=2, dtype=float).reshape(2,3)
print(a)
print(f'a.shape:{a.shape}')
print(f'a.ndim: {a.ndim}')

[[ 1.  3.  5.]
 [ 7.  9. 11.]]
a.shape:(2, 3)
a.ndim: 2
