# 从菜鸟教程上面练习 Python 库的 Numpy 的使用

In [21]:
# numpy从数值范围来创建数组
import numpy as np

print(f"Numpy的版本号：{np.__version__}")

a = np.array([1,2,3,4,5])
print(a)

Numpy的版本号：1.26.4
[1 2 3 4 5]


In [2]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


Numpy的 `asarray` 和 `array` 有什么区别呢？
`numpy.asarray` 和 `numpy.array` 都可以用于将输入数据转换为一个NumPy的`ndarray`，但它们在处理输入数据时有一些关键的区别：

1. **复制行为**：
   - `numpy.array` 默认会尝试复制输入数据，即使输入已经是`ndarray`类型。这意味着，使用`numpy.array`创建的新数组是一个新的副本，对新数组的修改不会影响原始数组。
   - `numpy.asarray` 则尝试重用现有的数据而不进行复制。如果输入数据已经是`ndarray`且没有指定不同的数据类型(`dtype`)或其他选项，则返回的是原始数组的一个视图(view)，而不是它的副本。这可以使内存使用更加高效。

2. **数据类型转换**：
   - 使用`numpy.array`时，可以通过`dtype`参数明确指定输出数组的数据类型。如果你不指定，它会尝试推断出合适的数据类型。
   - `numpy.asarray`同样支持通过`dtype`参数指定数据类型，但是当输入已经是具有相同数据类型的`ndarray`时，它不会创建一个新的数组或改变其数据类型。

3. **子类处理**：
   - `numpy.array` 不会自动将输入的子类实例转换为`ndarray`，除非你设置了`subok=True`。
   - `numpy.asarray` 通常会试图返回一个基础的`ndarray`对象，即使输入是某个`ndarray`子类的实例。

简单来说，如果你确定你的输入已经是`ndarray`并且不需要更改其数据类型，使用`asarray`可能更有效率因为它避免了不必要的复制。而当你需要确保得到一个新的副本或者想要明确控制输出数组的数据类型时，`numpy.array`则更为合适。

当然可以。为了更清楚地展示`numpy.array`和`numpy.asarray`之间的区别，我们可以通过几个简单的例子来说明它们在不同场景下的行为。

### 示例 1: 使用 `numpy.array`

假设我们有一个已经存在的NumPy数组，并且我们想要使用`numpy.array`创建它的副本：

```python
import numpy as np

# 原始数组
original_array = np.array([1, 2, 3])

# 使用 numpy.array 创建副本
array_copy = np.array(original_array)

# 修改副本中的值
array_copy[0] = 99

print("Original array:", original_array)  # 输出: [1 2 3]
print("Array copy:", array_copy)         # 输出: [99  2  3]
```

在这个例子中，我们可以看到对`array_copy`的修改并不会影响到`original_array`，因为`np.array()`函数默认情况下会创建一个新的副本。

### 示例 2: 使用 `numpy.asarray`

现在，让我们看看使用`numpy.asarray`的情况：

```python
import numpy as np

# 原始数组
original_array = np.array([1, 2, 3])

# 使用 numpy.asarray 尝试重用原始数据
array_view = np.asarray(original_array)

# 修改通过 asarray 得到的数组中的值
array_view[0] = 99

print("Original array:", original_array)  # 输出: [99  2  3]
print("Array view:", array_view)          # 输出: [99  2  3]
```

这里，当我们尝试通过`numpy.asarray`从`original_array`创建一个新数组时，由于`original_array`已经是`ndarray`类型并且没有指定不同的`dtype`，`numpy.asarray`实际上返回的是原始数组的一个视图而不是副本。因此，对`array_view`所做的任何更改都会反映在`original_array`上。

### 总结

- 如果你需要确保操作不会影响原始数组（即需要一个独立的副本），应该使用`numpy.array`。
- 如果你希望避免不必要的复制以节省内存或提高效率，并且不介意对数组的更改可能会影响到原始数组（当输入已经是`ndarray`时），那么`numpy.asarray`是一个更好的选择。

这些例子展示了如何根据具体需求选择合适的函数来处理NumPy数组，从而优化性能并避免意外的数据变更。

In [48]:
import numpy as np
a = np.asarray([1,2,3])
print(a)

[1 2 3]


In [14]:
import numpy as np

a = np.arange(10, dtype=float)
print(a)
print(f'a.shape: {a.shape}')
print(f'a.ndim: {a.ndim}')
print(f'a[1]: {a[1]: .3f}')

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a.shape: (10,)
a.ndim: 1
a[1]:  1.000


In [20]:
import numpy as np

a = np.arange(start=1, stop=12, step=2, dtype=float).reshape(2,3)
print(a)
print(f'a.shape:{a.shape}')
print(f'a.ndim: {a.ndim}')
print(f'a.type: { type(a)}')

[[ 1.  3.  5.]
 [ 7.  9. 11.]]
a.shape:(2, 3)
a.ndim: 2
a.type: <class 'numpy.ndarray'>


Numpy 的 `zeros` 函数

In [ ]:
import numpy as np

a = np.array([1,2,3])
# 可以看出 dtype默认是 float
b = np.zeros(a.shape, dtype=float)
print(b)

a= np.array([[1,2,3],[1,2,4]])
c = np.zeros(a.shape, dtype=int)
print(c)

[0. 0. 0.]
[[0 0 0]
 [0 0 0]]


Numpy 的 `empty` 函数， 生成出来的 `ndarray` 是随机的，那么是否可以指定随机数的范围呢？  
答案是可以，使用 `numpy.random.rand` 或者 `numpy.random.uniform` 等

In [34]:
import numpy as np

a = np.array([1,2,3])

b = np.empty(a.shape, dtype=float)
print(b)

[4.24399158e-314 2.12199579e-314 8.48798316e-314]


生成有指定范围的随机数的ndarray

In [37]:
import numpy as np
a = np.array([1,2,3])
b = np.random.rand(*a.shape)  # 生成0-1之间的随机数
print(b)    

[0.5105549  0.46706985 0.25997961]


Numpy的 `ones` 函数，生成出来的数字全部用1来填充

In [47]:
import numpy as np

a = np.ones(shape=(2,3), dtype=float)
print(a)

b = np.ones_like(a, dtype=int)
print(b)

c = np.ones_like(a=a, dtype=float, shape=(1,10))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
from elasticsearch import Elasticsearch

es = Elasticsearch(["http://10.10.4.121:9200"])

print(es.ping())  # 应该返回 True
info = es.info()
print(info['version']['number'])  # 应该输出 7.6.2

True
7.6.2


In [1]:
import elasticsearch

print(elasticsearch.__version__)

(7, 13, 0)
